Repository joelbarbeiro/WayPinPoint, pull requests merged in 2024-11, with the labels that each got.

#9 #53: My profile fragment creation
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MyProfileFragment.java
  MobileApp/app/src/main/res/layout/activity_login.xml
  MobileApp/app/src/main/res/layout/activity_register.xml
  MobileApp/app/src/main/res/layout/fragment_my_profile.xml
  MobileApp/app/src/main/res/values/strings.xml
Labels: feature

#13 #10 manage roles
  WebApp/yii-application/backend/controllers/RoleRegisterController.php
  WebApp/yii-application/backend/controllers/SiteController.php
  WebApp/yii-application/backend/models/RoleRegisterForm.php
  WebApp/yii-application/backend/views/layouts/sidebar.php
  WebApp/yii-application/backend/views/roleregister/roleregister.php
  WebApp/yii-application/backend/views/site/assign-role.php
  WebApp/yii-application/backend/views/site/index.php
  WebApp/yii-application/common/models/User.php
Labels: feature

#14 #56 visualize activities index
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/web/.htaccess
  WebApp/yii-application/common/models/User.php
  WebApp/yii-application/common/models/UserSearch.php
  WebApp/yii-application/frontend/config/main.php
  WebApp/yii-application/frontend/controllers/ActivityController.php
  WebApp/yii-application/frontend/controllers/UserController.php
  WebApp/yii-application/frontend/models/Activity.php
  WebApp/yii-application/frontend/models/ActivitySearch.php
  WebApp/yii-application/frontend/views/activity/_search.php
  WebApp/yii-application/frontend/views/activity/index.php
  WebApp/yii-application/frontend/views/activity/view.php
  WebApp/yii-application/frontend/views/layouts/main.php
  WebApp/yii-application/frontend/views/user/_form.php
  WebApp/yii-application/frontend/views/user/update.php
  WebApp/yii-application/frontend/views/user/view.php
  WebApp/yii-application/frontend/web/.htaccess
Labels: feature

#15 Web/54 crud activity
  WebApp/migrations.php
  WebApp/yii-application/backend/controllers/ActivitiesController.php
  WebApp/yii-application/backend/controllers/CalendarController.php
  WebApp/yii-application/backend/controllers/RegisterController.php
  WebApp/yii-application/backend/controllers/SiteController.php
  WebApp/yii-application/backend/models/Activities.php
  WebApp/yii-application/backend/models/ActivitiesSearch.php
  WebApp/yii-application/backend/models/Bookings.php
  WebApp/yii-application/backend/models/Calendar.php
  WebApp/yii-application/backend/models/CalendarSearch.php
  WebApp/yii-application/backend/models/Dates.php
  WebApp/yii-application/backend/models/Invoices.php
  WebApp/yii-application/backend/models/Localsellpoint.php
  WebApp/yii-application/backend/models/Pictures.php
  WebApp/yii-application/backend/models/Sales.php
  WebApp/yii-application/backend/models/Tickets.php
  WebApp/yii-application/backend/models/Times.php
  WebApp/yii-application/backend/models/Userextras.php
  WebApp/yii-application/backend/views/activities/_form.php
  WebApp/yii-application/backend/views/activities/_search.php
  WebApp/yii-application/backend/views/activities/create.php
  WebApp/yii-application/backend/views/activities/index.php
  WebApp/yii-application/backend/views/activities/update.php
  WebApp/yii-application/backend/views/activities/view.php
  WebApp/yii-application/backend/views/calendar/_form.php
  WebApp/yii-application/backend/views/calendar/_search.php
  WebApp/yii-application/backend/views/calendar/create.php
  WebApp/yii-application/backend/views/calendar/index.php
  WebApp/yii-application/backend/views/calendar/update.php
  WebApp/yii-application/backend/views/calendar/view.php
  WebApp/yii-application/backend/views/layouts/main.php
  WebApp/yii-application/backend/views/layouts/sidebar.php
  WebApp/yii-application/backend/views/user/index.php
  WebApp/yii-application/console/migrations/m241103_150521_create_userextras_table.php
Labels: feature

#16 #11: Register local sellpoint
  WebApp/yii-application/backend/controllers/LocalsellpointController.php
  WebApp/yii-application/backend/models/Localsellpoint.php
  WebApp/yii-application/backend/models/LocalsellpointSearch.php
  WebApp/yii-application/backend/models/Userextras.php
  WebApp/yii-application/backend/views/layouts/sidebar.php
  WebApp/yii-application/backend/views/localsellpoint/_form.php
  WebApp/yii-application/backend/views/localsellpoint/_search.php
  WebApp/yii-application/backend/views/localsellpoint/create.php
  WebApp/yii-application/backend/views/localsellpoint/index.php
  WebApp/yii-application/backend/views/localsellpoint/update.php
  WebApp/yii-application/backend/views/localsellpoint/view.php
  WebApp/yii-application/console/migrations/m241105_192257_add_manager_id_column_to_localsellpoint_table.php
Labels: feature

#17 #59: Assign new users with supplier
  WebApp/yii-application/backend/controllers/LocalsellpointController.php
  WebApp/yii-application/backend/controllers/RoleRegisterController.php
  WebApp/yii-application/backend/models/RoleRegisterForm.php
  WebApp/yii-application/backend/views/localsellpoint/create.php
  WebApp/yii-application/backend/views/roleregister/roleregister.php
  WebApp/yii-application/common/models/UserExtra.php
Labels: enhancement

#18 #59- Assign new users with supplier
  WebApp/yii-application/backend/controllers/LocalsellpointController.php
Labels: enhancement

#19 #00- Migrations
  WebApp/yii-application/console/migrations/m241027_181850_create_calendar_table.php
  WebApp/yii-application/console/migrations/m241105_192257_add_manager_id_column_to_localsellpoint_table.php
  WebApp/yii-application/console/migrations/m241107_200327_add_localsellpoint_id_nif_address_to_table_userextras.php
  WebApp/yii-application/console/migrations/m241107_204534_add_hour_id_to_table_dates.php
  WebApp/yii-application/frontend/controllers/ActivityController.php
  WebApp/yii-application/frontend/views/activity/_search.php
  WebApp/yii-application/frontend/views/activity/index.php
  WebApp/yii-application/frontend/views/activity/view.php
Labels: migrations

#20 #58: protect backoffice from frontoffice users
  WebApp/yii-application/backend/controllers/ActivitiesController.php
  WebApp/yii-application/backend/controllers/CalendarController.php
  WebApp/yii-application/backend/controllers/LocalsellpointController.php
  WebApp/yii-application/backend/controllers/RoleRegisterController.php
  WebApp/yii-application/backend/controllers/SiteController.php
  WebApp/yii-application/backend/views/site/error.php
Labels: enhancement
