Repository joelbarbeiro/WayPinPoint, pull requests merged in 2025-01, with the labels that each got.

#76 #69 - Fixed Update and Add Endpoints, now working as intended
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
Labels: API

#78 #33 - Checkout Ticket
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
  WebApp/yii-application/backend/modules/api/views/default/receipt.php
  WebApp/yii-application/common/models/Activity.php
Labels: enhancement, feature

#79 # 77 mqtt server
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/controllers/ActivityController.php
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/composer.lock
  WebApp/yii-application/console/controllers/RbacController.php
  WebApp/yii-application/console/migrations/m241126_214056_add_localsellpoint_to_sale.php
Labels: feature

#84 #30: Real time photos
  MobileApp/app/src/main/AndroidManifest.xml
  MobileApp/app/src/main/java/Listeners/CartListener.java
  MobileApp/app/src/main/java/Listeners/CartsListener.java
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityPhotosFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListReviewsFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/res/layout/fragment_activity_photos.xml
  MobileApp/app/src/main/res/layout/fragment_cart.xml
  MobileApp/app/src/main/res/layout/fragment_list_activities.xml
  MobileApp/app/src/main/res/layout/fragment_list_reviews.xml
  MobileApp/app/src/main/res/layout/item_empty_view.xml
  MobileApp/app/src/main/res/menu/menu_main.xml
  MobileApp/app/src/main/res/values/strings.xml
  WebApp/tests/_support/_generated/AcceptanceTesterActions.php
Labels: enhancement, feature

#85 #69 - Crud Cart
  MobileApp/app/src/main/java/Adapters/CartAdapter.java
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/Model/WaypinpointDbHelper.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartFragment.java
  MobileApp/app/src/main/res/layout/fragment_cart.xml
  MobileApp/app/src/main/res/values/strings.xml
Labels: bug

#86 #30: Real time photos
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityCreateActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityPhotosFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ApiHostnameSetupActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListReviewsFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/LoginActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MyActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/QRCodeScannerActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  MobileApp/app/src/main/res/layout/activity_api_hostname_setup.xml
  MobileApp/app/src/main/res/layout/activity_create.xml
  MobileApp/app/src/main/res/layout/activity_login.xml
  MobileApp/app/src/main/res/layout/activity_register.xml
  MobileApp/app/src/main/res/layout/cart_details_activity.xml
  MobileApp/app/src/main/res/layout/fragment_activity_photos.xml
  MobileApp/app/src/main/res/layout/fragment_cart.xml
  MobileApp/app/src/main/res/layout/fragment_list_reviews.xml
  MobileApp/app/src/main/res/layout/fragment_my_activities.xml
  MobileApp/app/src/main/res/layout/item_list_activity.xml
  MobileApp/app/src/main/res/layout/item_list_cart.xml
  MobileApp/app/src/main/res/layout/item_list_create_activity.xml
  MobileApp/app/src/main/res/layout/item_list_review.xml
  MobileApp/app/src/main/res/layout/item_photo_list.xml
  MobileApp/app/src/main/res/layout/nav_header_main.xml
  MobileApp/app/src/main/res/values/strings.xml
Labels: enhancement

#88 #33: Checkout ticket
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/LoginActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MyProfileActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/RegisterActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  MobileApp/app/src/main/res/values/strings.xml
Labels: bug, enhancement

#91 #78: MQTT Subs
  MobileApp/app/src/main/java/Model/MQTTManager.java
  MobileApp/app/src/main/java/Model/MqttNotificationManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/modules/api/controllers/ReviewController.php
  WebApp/yii-application/frontend/controllers/CartController.php
  WebApp/yii-application/frontend/models/Review.php
Labels: feature

#92 - End point Invoices
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/modules/api/controllers/InvoiceController.php
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/common/models/Invoice.php
Labels: API

#93 Web/69 crud cart
  WebApp/yii-application/backend/config/test.php
  WebApp/yii-application/common/config/test.php
  WebApp/yii-application/common/models/Cart.php
  WebApp/yii-application/common/tests/unit/CartTest.php
  WebApp/yii-application/frontend/config/test.php
  WebApp/yii-application/frontend/tests/_support/AcceptanceTester.php
  WebApp/yii-application/frontend/tests/acceptance.suite.yml
  WebApp/yii-application/frontend/tests/acceptance/HomeCest.php
  WebApp/yii-application/frontend/tests/unit/CartTest.php
Labels: tests

#94 #69 - Finished Functional and Acceptance Tests
  WebApp/yii-application/composer.json
  WebApp/yii-application/composer.lock
  WebApp/yii-application/frontend/tests/acceptance.suite.yml
  WebApp/yii-application/frontend/tests/acceptance/HomeCest.php
  WebApp/yii-application/frontend/tests/acceptance/WaypinPointCest.php
  WebApp/yii-application/frontend/tests/functional.suite.yml
  WebApp/yii-application/frontend/tests/functional/CreateCartCest.php
  WebApp/yii-application/frontend/views/layouts/main.php
  WebApp/yii-application/frontend/views/review/_form.php
Labels: tests

#96 Web/77 mqtt server
  WebApp/yii-application/backend/config/test.php
  WebApp/yii-application/backend/tests/_bootstrap.php
  WebApp/yii-application/backend/tests/_support/FunctionalTester.php
  WebApp/yii-application/backend/tests/functional.suite.yml
  WebApp/yii-application/backend/tests/functional/CreateActivityCest.php
  WebApp/yii-application/backend/tests/functional/LoginCest.php
  WebApp/yii-application/backend/tests/unit.suite.yml
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/common/tests/unit/ActivityTest.php
  WebApp/yii-application/composer.json
  WebApp/yii-application/composer.lock
  WebApp/yii-application/frontend/config/test.php
  WebApp/yii-application/frontend/tests/_bootstrap.php
Labels: tests

#97 Web/69 crud cart
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/controllers/SaleController.php
  WebApp/yii-application/backend/views/sale/index.php
  WebApp/yii-application/common/models/Cart.php
  WebApp/yii-application/common/models/Invoice.php
  WebApp/yii-application/frontend/views/cart/_form.php
  WebApp/yii-application/frontend/views/cart/index.php
  WebApp/yii-application/frontend/views/invoice/index.php
  WebApp/yii-application/frontend/views/ticket/index.php
  WebApp/yii-application/frontend/views/ticket/view.php
Labels: bug, enhancement

#99 #69 - Crud Cart
  WebApp/yii-application/backend/views/activity/_form.php
  WebApp/yii-application/backend/views/site/login.php
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/common/models/Booking.php
  WebApp/yii-application/common/models/UserExtra.php
  WebApp/yii-application/frontend/controllers/CartController.php
  WebApp/yii-application/frontend/views/activity/index.php
  WebApp/yii-application/frontend/views/cart/_form.php
  WebApp/yii-application/frontend/views/cart/index.php
  WebApp/yii-application/frontend/views/site/signup.php
Labels: bug, enhancement, feature

#100 - Calendar test
  WebApp/yii-application/backend/tests/functional/CreateActivityCest.php
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/common/tests/unit/ActivityTest.php
  WebApp/yii-application/frontend/views/activity/index.php
Labels: tests

#101 - Calendar test
  WebApp/yii-application/backend/tests/_data/testFile.jpg
  WebApp/yii-application/common/tests/unit/CalendarTest.php
Labels: tests

#102 #100 functional tests
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
  WebApp/yii-application/common/models/Booking.php
  WebApp/yii-application/common/models/Cart.php
  WebApp/yii-application/common/models/Ticket.php
  WebApp/yii-application/console/controllers/RbacController.php
  WebApp/yii-application/console/migrations/m250107_191557_create_bookingid_table_ticket.php
  WebApp/yii-application/frontend/controllers/CartController.php
  WebApp/yii-application/frontend/controllers/TicketController.php
  WebApp/yii-application/frontend/tests/unit/CartTest.php
  WebApp/yii-application/frontend/views/activity/index.php
  WebApp/yii-application/frontend/views/activity/view.php
  WebApp/yii-application/frontend/views/ticket/index.php
  WebApp/yii-application/frontend/views/ticket/printticket.php
  WebApp/yii-application/frontend/views/ticket/view.php
Labels: bug, enhancement

#103 #69 - Fixed CartTest
  WebApp/yii-application/common/tests/unit/CartTest.php
Labels: tests

#107 #100: functional tests
  WebApp/yii-application/backend/views/roleregister/roleregister.php
  WebApp/yii-application/backend/views/site/login.php
  WebApp/yii-application/backend/web/css/site.css
  WebApp/yii-application/frontend/views/activity/index.php
Labels: enhancement

#108 - Get pdf invoice from backend
  WebApp/yii-application/backend/controllers/SaleController.php
  WebApp/yii-application/backend/views/sale/index.php
  WebApp/yii-application/backend/views/sale/invoice.php
  WebApp/yii-application/common/models/Invoice.php
  WebApp/yii-application/common/models/Sale.php
  WebApp/yii-application/common/models/UserExtra.php
  WebApp/yii-application/composer.lock
Labels: feature

#109 69 Crud Cart
  WebApp/yii-application/backend/controllers/SaleController.php
  WebApp/yii-application/backend/views/sale/receipt.php
  WebApp/yii-application/backend/views/sale/view.php
  WebApp/yii-application/common/models/Invoice.php
  WebApp/yii-application/common/models/Sale.php
Labels: bug, enhancement

#110 #100 - Testing
  WebApp/yii-application/backend/controllers/SaleController.php
  WebApp/yii-application/frontend/views/invoice/printinvoice.php
  WebApp/yii-application/frontend/views/review/index.php
Labels: enhancement

#111 #100 - Testing
  WebApp/yii-application/backend/models/RegisterForm.php
  WebApp/yii-application/backend/models/RoleRegisterForm.php
  WebApp/yii-application/backend/views/sale/invoice.php
Labels: enhancement

#112 - image resize
  WebApp/yii-application/backend/web/img/activity/2/8CqDvPuo_kI.jpg
  WebApp/yii-application/backend/web/img/activity/2/GxxHf3fJYPI.jpg
  WebApp/yii-application/backend/web/img/activity/2/WLxQvbMyfas.jpg
  WebApp/yii-application/backend/web/img/activity/2/WvDYdXDzkhs.jpg
  WebApp/yii-application/backend/web/img/activity/2/ed-XvG01qV-0.jpg
  WebApp/yii-application/backend/web/img/activity/2/yBXF8NNlHcg.jpg
  WebApp/yii-application/backend/web/img/activity/3/7qTA0RDgXb0.jpg
  WebApp/yii-application/backend/web/img/activity/3/8T7NG5tvC8E.jpg
  WebApp/yii-application/backend/web/img/activity/3/ITjiVXcwVng.jpg
  WebApp/yii-application/backend/web/img/activity/3/J6cg9TA8-e8.jpg
  WebApp/yii-application/backend/web/img/activity/3/LR5-OExz4eE.jpg
  WebApp/yii-application/backend/web/img/activity/3/MBz7o-W8kUE.jpg
  WebApp/yii-application/backend/web/img/activity/3/V6s1cmE39XM.jpg
  WebApp/yii-application/backend/web/img/activity/3/ZHVqVY1NZJQ.jpg
  WebApp/yii-application/common/models/Activity.php
  WebApp/yii-application/frontend/web/img/activity/2/8CqDvPuo_kI.jpg
  WebApp/yii-application/frontend/web/img/activity/2/GxxHf3fJYPI.jpg
  WebApp/yii-application/frontend/web/img/activity/2/WLxQvbMyfas.jpg
  WebApp/yii-application/frontend/web/img/activity/2/WvDYdXDzkhs.jpg
  WebApp/yii-application/frontend/web/img/activity/2/ed-XvG01qV-0.jpg
  WebApp/yii-application/frontend/web/img/activity/2/yBXF8NNlHcg.jpg
  WebApp/yii-application/frontend/web/img/activity/3/7qTA0RDgXb0.jpg
  WebApp/yii-application/frontend/web/img/activity/3/8T7NG5tvC8E.jpg
  WebApp/yii-application/frontend/web/img/activity/3/ITjiVXcwVng.jpg
  WebApp/yii-application/frontend/web/img/activity/3/J6cg9TA8-e8.jpg
  WebApp/yii-application/frontend/web/img/activity/3/LR5-OExz4eE.jpg
  WebApp/yii-application/frontend/web/img/activity/3/MBz7o-W8kUE.jpg
  WebApp/yii-application/frontend/web/img/activity/3/V6s1cmE39XM.jpg
  WebApp/yii-application/frontend/web/img/activity/3/ZHVqVY1NZJQ.jpg
Labels: enhancement

#113 #100: Invoices
  MobileApp/app/src/main/AndroidManifest.xml
  MobileApp/app/src/main/java/Adapters/InvoiceListAdapter.java
  MobileApp/app/src/main/java/Listeners/InvoicesListener.java
  MobileApp/app/src/main/java/Model/Invoice.java
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/Model/WaypinpointDbHelper.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/InvoiceDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListInvoicesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/InvoiceJsonParser.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  MobileApp/app/src/main/res/drawable-anydpi/ic_invoice_list.xml
  MobileApp/app/src/main/res/drawable-hdpi/ic_invoice_list.png
  MobileApp/app/src/main/res/drawable-mdpi/ic_invoice_list.png
  MobileApp/app/src/main/res/drawable-xhdpi/ic_invoice_list.png
  MobileApp/app/src/main/res/drawable-xxhdpi/ic_invoice_list.png
  MobileApp/app/src/main/res/layout/activity_invoice_details.xml
  MobileApp/app/src/main/res/layout/fragment_list_invoices.xml
  MobileApp/app/src/main/res/layout/item_list_invoice.xml
  MobileApp/app/src/main/res/menu/menu_main.xml
  MobileApp/app/src/main/res/values/strings.xml
Labels: feature

#114 #69 - Now properly sending the right dates when added to cart
  MobileApp/app/src/main/java/Model/WaypinpointDbHelper.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
Labels: bug, enhancement

#115 - Generate a pdf from invoice details
  MobileApp/app/src/main/AndroidManifest.xml
  MobileApp/app/src/main/java/Model/PdfGenerator.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/InvoiceDetailsActivity.java
  MobileApp/app/src/main/res/layout/activity_invoice_details.xml
Labels: feature

#116 #69 - Crud Cart
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/Model/WaypinpointDbHelper.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
Labels: enhancement, feature

#117 #69 - Fixed stock control through API
  WebApp/yii-application/backend/modules/api/controllers/ActivityController.php
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
Labels: enhancement, feature

#118 #100: Fixes
  MobileApp/app/src/main/java/Model/MqttNotificationManager.java
  MobileApp/app/src/main/java/Model/Route.java
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListInvoicesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MyActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/QRCodeScannerActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  MobileApp/app/src/main/res/drawable-anydpi/ic_pdf.xml
  MobileApp/app/src/main/res/drawable-hdpi/ic_pdf.png
  MobileApp/app/src/main/res/drawable-mdpi/ic_pdf.png
  MobileApp/app/src/main/res/drawable-xhdpi/ic_pdf.png
  MobileApp/app/src/main/res/drawable-xxhdpi/ic_pdf.png
  MobileApp/app/src/main/res/layout/activity_invoice_details.xml
  MobileApp/app/src/main/res/layout/fragment_my_activities.xml
  MobileApp/app/src/main/res/values/strings.xml
  WebApp/yii-application/backend/controllers/SiteController.php
  WebApp/yii-application/common/models/ActivitySearch.php
  WebApp/yii-application/frontend/views/activity/index.php
  WebApp/yii-application/frontend/views/layouts/main.php
Labels: bug, enhancement

#119 Mobile/101 generate pdf
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityCreateActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListActivitiesFragment.java
  MobileApp/app/src/main/res/layout/fragment_list_activities.xml
  MobileApp/app/src/main/res/values/strings.xml
  WebApp/yii-application/backend/web/img/activity/3/LR5-OExz4eE.jpg
  WebApp/yii-application/backend/web/img/activity/3/MBz7o-W8kUE.jpg
Labels: bug

#120 - fixed activity save
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityCreateActivity.java
  MobileApp/app/src/main/res/values/strings.xml
Labels: bug

#121 #100: Fixes
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ActivityPhotosFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/DateTimeActivityCreateFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListInvoicesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ListReviewsFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MyActivitiesFragment.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/ReviewDetailsActivity.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/utils/Utilities.java
  MobileApp/app/src/main/res/layout/fragment_date_time_activity_create.xml
  MobileApp/app/src/main/res/layout/fragment_my_activities.xml
  MobileApp/app/src/main/res/values/strings.xml
Labels: bug, enhancement

#122 #69 - Crud Cart
  WebApp/yii-application/backend/config/main.php
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
Labels: bug, API

#123 #69 Crud Cart
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/CartDetailsActivity.java
Labels: API

#125 #69 Crud Cart
  WebApp/yii-application/backend/modules/api/controllers/CartController.php
Labels: enhancement, API

#126 69 Crud Cart
  MobileApp/app/src/main/java/Model/SingletonManager.java
Labels: enhancement
