Repository joelbarbeiro/WayPinPoint, pull requests merged in 2025-02, with the labels that each got.

#127 #69 - Added back button and bug fixes
  MobileApp/app/src/main/AndroidManifest.xml
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
Labels: bug, enhancement

#129 #100: Fixes
  MobileApp/app/src/main/AndroidManifest.xml
  MobileApp/app/src/main/java/Model/SingletonManager.java
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/MenuMainActivity.java
  MobileApp/app/src/main/res/menu/menu_main.xml
Labels: enhancement

#130 #100: Fixes
  MobileApp/app/src/main/java/Model/PdfGenerator.java
Labels: bug

#131 #100: Fixes
  MobileApp/app/src/main/java/pt/ipleiria/estg/dei/waypinpoint/QRCodeScannerActivity.java
  WebApp/yii-application/backend/controllers/BookingController.php
Labels: bug
